export interface WattBoxInfo {
    host_name: Array<string>,
    hardware_version: Array<string>,
    serial_number: Array<string>,
    site_ip: Array<string>,
    connect_status: Array<string>,
    site_lost_status: Array<string>,
    auto_reboot: Array<string>,
    outlet_name: Array<string>,
    outlet_method: Array<string>,
    outlet_status: Array<string>,
    led_status: Array<string>,
    safe_voltage_status: Array<string>,
    voltage_value: Array<string>,
    current_value: Array<string>,
    power_value: Array<string>,
    cloud_status: Array<string>,
    hasUPS: Array<string>,
    audible_alarm: Array<string>,
    est_run_time: Array<string>,
    battery_test: Array<string>,
    battery_health: Array<string>,
    battery_charge: Array<string>,
    battery_load: Array<string>,
    power_lost: Array<string>,
    mute: Array<string>
}